# Generated by Django 4.1 on 2023-12-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="url",
            field=models.TextField(default="", max_length=100),
        ),
    ]
